// Generated by gencpp from file shared_msgs/imu_msg.msg
// DO NOT EDIT!


#ifndef SHARED_MSGS_MESSAGE_IMU_MSG_H
#define SHARED_MSGS_MESSAGE_IMU_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shared_msgs
{
template <class ContainerAllocator>
struct imu_msg_
{
  typedef imu_msg_<ContainerAllocator> Type;

  imu_msg_()
    : gyro()
    , accel()  {
      gyro.assign(0.0);

      accel.assign(0.0);
  }
  imu_msg_(const ContainerAllocator& _alloc)
    : gyro()
    , accel()  {
  (void)_alloc;
      gyro.assign(0.0);

      accel.assign(0.0);
  }



   typedef boost::array<float, 3>  _gyro_type;
  _gyro_type gyro;

   typedef boost::array<float, 3>  _accel_type;
  _accel_type accel;





  typedef boost::shared_ptr< ::shared_msgs::imu_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shared_msgs::imu_msg_<ContainerAllocator> const> ConstPtr;

}; // struct imu_msg_

typedef ::shared_msgs::imu_msg_<std::allocator<void> > imu_msg;

typedef boost::shared_ptr< ::shared_msgs::imu_msg > imu_msgPtr;
typedef boost::shared_ptr< ::shared_msgs::imu_msg const> imu_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shared_msgs::imu_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shared_msgs::imu_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shared_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'shared_msgs': ['/home/eric/Desktop/ROV/X12-Core/surface/src/ros/src/shared_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shared_msgs::imu_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shared_msgs::imu_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_msgs::imu_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_msgs::imu_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_msgs::imu_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_msgs::imu_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shared_msgs::imu_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce45cc38daa7ab1aa2192631b286b0ce";
  }

  static const char* value(const ::shared_msgs::imu_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce45cc38daa7ab1aULL;
  static const uint64_t static_value2 = 0xa2192631b286b0ceULL;
};

template<class ContainerAllocator>
struct DataType< ::shared_msgs::imu_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shared_msgs/imu_msg";
  }

  static const char* value(const ::shared_msgs::imu_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shared_msgs::imu_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] gyro\n\
float32[3] accel\n\
\n\
";
  }

  static const char* value(const ::shared_msgs::imu_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shared_msgs::imu_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gyro);
      stream.next(m.accel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imu_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shared_msgs::imu_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shared_msgs::imu_msg_<ContainerAllocator>& v)
  {
    s << indent << "gyro[]" << std::endl;
    for (size_t i = 0; i < v.gyro.size(); ++i)
    {
      s << indent << "  gyro[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gyro[i]);
    }
    s << indent << "accel[]" << std::endl;
    for (size_t i = 0; i < v.accel.size(); ++i)
    {
      s << indent << "  accel[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.accel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHARED_MSGS_MESSAGE_IMU_MSG_H
