// Generated by gencpp from file shared_msgs/tools_command_msg.msg
// DO NOT EDIT!


#ifndef SHARED_MSGS_MESSAGE_TOOLS_COMMAND_MSG_H
#define SHARED_MSGS_MESSAGE_TOOLS_COMMAND_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shared_msgs
{
template <class ContainerAllocator>
struct tools_command_msg_
{
  typedef tools_command_msg_<ContainerAllocator> Type;

  tools_command_msg_()
    : manipulator(0)
    , groutTrout(0)
    , liftBag(0)
    , marker(0)  {
    }
  tools_command_msg_(const ContainerAllocator& _alloc)
    : manipulator(0)
    , groutTrout(0)
    , liftBag(0)
    , marker(0)  {
  (void)_alloc;
    }



   typedef int8_t _manipulator_type;
  _manipulator_type manipulator;

   typedef int8_t _groutTrout_type;
  _groutTrout_type groutTrout;

   typedef int8_t _liftBag_type;
  _liftBag_type liftBag;

   typedef int8_t _marker_type;
  _marker_type marker;





  typedef boost::shared_ptr< ::shared_msgs::tools_command_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shared_msgs::tools_command_msg_<ContainerAllocator> const> ConstPtr;

}; // struct tools_command_msg_

typedef ::shared_msgs::tools_command_msg_<std::allocator<void> > tools_command_msg;

typedef boost::shared_ptr< ::shared_msgs::tools_command_msg > tools_command_msgPtr;
typedef boost::shared_ptr< ::shared_msgs::tools_command_msg const> tools_command_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shared_msgs::tools_command_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shared_msgs::tools_command_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shared_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'shared_msgs': ['/home/eric/Desktop/ROV/X12-Core/surface/src/ros/src/shared_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shared_msgs::tools_command_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shared_msgs::tools_command_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_msgs::tools_command_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_msgs::tools_command_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_msgs::tools_command_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_msgs::tools_command_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shared_msgs::tools_command_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99400b8a44513c5ef4f0bf7e444e5295";
  }

  static const char* value(const ::shared_msgs::tools_command_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99400b8a44513c5eULL;
  static const uint64_t static_value2 = 0xf4f0bf7e444e5295ULL;
};

template<class ContainerAllocator>
struct DataType< ::shared_msgs::tools_command_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shared_msgs/tools_command_msg";
  }

  static const char* value(const ::shared_msgs::tools_command_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shared_msgs::tools_command_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 manipulator\n\
int8 groutTrout\n\
int8 liftBag\n\
int8 marker\n\
\n\
";
  }

  static const char* value(const ::shared_msgs::tools_command_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shared_msgs::tools_command_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.manipulator);
      stream.next(m.groutTrout);
      stream.next(m.liftBag);
      stream.next(m.marker);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tools_command_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shared_msgs::tools_command_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shared_msgs::tools_command_msg_<ContainerAllocator>& v)
  {
    s << indent << "manipulator: ";
    Printer<int8_t>::stream(s, indent + "  ", v.manipulator);
    s << indent << "groutTrout: ";
    Printer<int8_t>::stream(s, indent + "  ", v.groutTrout);
    s << indent << "liftBag: ";
    Printer<int8_t>::stream(s, indent + "  ", v.liftBag);
    s << indent << "marker: ";
    Printer<int8_t>::stream(s, indent + "  ", v.marker);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHARED_MSGS_MESSAGE_TOOLS_COMMAND_MSG_H
