(cl:in-package shared_msgs-msg)
(cl:export '(RX_AXIS-VAL
          RX_AXIS
          RY_AXIS-VAL
          RY_AXIS
          LX_AXIS-VAL
          LX_AXIS
          LY_AXIS-VAL
          LY_AXIS
          A-VAL
          A
          B-VAL
          B
          X-VAL
          X
          Y-VAL
          Y
          DPADX-VAL
          DPADX
          DPADY-VAL
          DPADY
          RB-VAL
          RB
          LB-VAL
          LB
          RTRIGGER-VAL
          RTRIGGER
          LTRIGGER-VAL
          LTRIGGER
))