# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from shared_msgs/auto_control_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class auto_control_msg(genpy.Message):
  _md5sum = "563a60a06dd4f4297aa17e367a4fb89b"
  _type = "shared_msgs/auto_control_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32[6] thrust_vec
bool[6] dims_locked
"""
  __slots__ = ['thrust_vec','dims_locked']
  _slot_types = ['float32[6]','bool[6]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       thrust_vec,dims_locked

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(auto_control_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.thrust_vec is None:
        self.thrust_vec = [0.] * 6
      if self.dims_locked is None:
        self.dims_locked = [False] * 6
    else:
      self.thrust_vec = [0.] * 6
      self.dims_locked = [False] * 6

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_6f().pack(*self.thrust_vec))
      buff.write(_get_struct_6B().pack(*self.dims_locked))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 24
      self.thrust_vec = _get_struct_6f().unpack(str[start:end])
      start = end
      end += 6
      self.dims_locked = _get_struct_6B().unpack(str[start:end])
      self.dims_locked = map(bool, self.dims_locked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.thrust_vec.tostring())
      buff.write(self.dims_locked.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 24
      self.thrust_vec = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=6)
      start = end
      end += 6
      self.dims_locked = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=6)
      self.dims_locked = map(bool, self.dims_locked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6B = None
def _get_struct_6B():
    global _struct_6B
    if _struct_6B is None:
        _struct_6B = struct.Struct("<6B")
    return _struct_6B
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
