# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from shared_msgs/final_thrust_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class final_thrust_msg(genpy.Message):
  _md5sum = "6ec19b411594e3b47b780fbf91db2d37"
  _type = "shared_msgs/final_thrust_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 hfl
uint8 hfr
uint8 hbr
uint8 hbl
uint8 vfl
uint8 vfr
uint8 vbr
uint8 vbl
"""
  __slots__ = ['hfl','hfr','hbr','hbl','vfl','vfr','vbr','vbl']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hfl,hfr,hbr,hbl,vfl,vfr,vbr,vbl

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(final_thrust_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.hfl is None:
        self.hfl = 0
      if self.hfr is None:
        self.hfr = 0
      if self.hbr is None:
        self.hbr = 0
      if self.hbl is None:
        self.hbl = 0
      if self.vfl is None:
        self.vfl = 0
      if self.vfr is None:
        self.vfr = 0
      if self.vbr is None:
        self.vbr = 0
      if self.vbl is None:
        self.vbl = 0
    else:
      self.hfl = 0
      self.hfr = 0
      self.hbr = 0
      self.hbl = 0
      self.vfl = 0
      self.vfr = 0
      self.vbr = 0
      self.vbl = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8B().pack(_x.hfl, _x.hfr, _x.hbr, _x.hbl, _x.vfl, _x.vfr, _x.vbr, _x.vbl))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.hfl, _x.hfr, _x.hbr, _x.hbl, _x.vfl, _x.vfr, _x.vbr, _x.vbl,) = _get_struct_8B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8B().pack(_x.hfl, _x.hfr, _x.hbr, _x.hbl, _x.vfl, _x.vfr, _x.vbr, _x.vbl))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.hfl, _x.hfr, _x.hbr, _x.hbl, _x.vfl, _x.vfr, _x.vbr, _x.vbl,) = _get_struct_8B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8B = None
def _get_struct_8B():
    global _struct_8B
    if _struct_8B is None:
        _struct_8B = struct.Struct("<8B")
    return _struct_8B
