module.exports = {
	STORE_UPDATED: 'STORE_UPDATED',
	UPDATE_STORE: 'UPDATE_STORE',
	CALIBRATE_CALL: 'CALIBRATE_CALL',
	CALIBRATE_RECEIVE: 'CALIBRATE_RECEIVE',
	GAMEPAD_STATE_UPDATED: 'GAMEPAD_STATE_UPDATED',

	SAMPLE_UPDATE: 'SAMPLE_UPDATE'
};